version: '3.8'

services:
  app:
    build: .
    container_name: jobostad-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./keys:/app/keys:ro
    depends_on:
      - postgres
      - redis
    networks:
      - jobostad-network

  postgres:
    image: postgres:latest
    container_name: jobostad-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ostad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jobostad-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobostad-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - jobostad-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: jobostad-redis
    ports:
      - "6379:6379"
    networks:
      - jobostad-network


networks:
  jobostad-network:

volumes:
  pgdata:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /mnt/pgdata/data
